.\"                                      Hey, EMACS: -*- nroff -*-
.TH NETADDR 1 "December 31, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
netaddr \- interactive shell for netaddr Python library
.SH DESCRIPTION
This manual page documents briefly the
.B netaddr
command. This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBnetaddr\fP is a Python library for the manipulation of various
common network address notations and representations.
.PP
The \fBnetaddr\fP command provides an interactive shell based on
\fBipython\fP allowing to work in a special environment where all
netaddr related commands are available without additional imports.
.SH OPTIONS
Any option accepted by \fBipython\fP is accepted by \fBnetaddr\fP.
.SH SEE ALSO
.BR ipython (1)
.IR /usr/share/doc/python-netaddr/api/
.SH AUTHOR
This manual page was written by Vincent Bernat <bernat@debian.org>,
for the Debian project (but may be used by others).
